[package]
name = "terror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
time = ["dep:chrono"]
err_id = ["dep:uuid"]

[dependencies]
chrono = { version = "0.4.19", optional = true }
uuid = { version = "1.0.0", features = ["v4"], optional = true }
