[package]
name = "terror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
time = ["dep:chrono"]
err_id = ["dep:uuid"]

[dependencies]
chrono = { version = "0.4.19", optional = true, features = ["serde"] }
uuid = { version = "1.0.0", features = ["v4", "serde"], optional = true }
serde = "1.0.137"
serde_json = "1.0.80"
serde_derive = "1.0.137"