name: test

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Run tests without features"
      run: cargo test --verbose
    - name: "Run tests with all features"
      run: cargo test --all-features --verbose
    - name: Build documentation
      run: cargo doc
